MVCFilmes2025/Models/ErrorViewModel.cs
namespace MVCFilmes2025.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCFilmes2025/Models/Filme.cs
using System.ComponentModel.DataAnnotations;

namespace MVCFilmes2025.Models
{
    public class Filme
    {
        public int ID { get; set; }

        [Display(Name = "Título")]
        [MaxLength(100)]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        public string Titulo { get; set; } = string.Empty;

        [Display(Name = "Data de lançamento")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [DataType(DataType.Date)]
        public DateTime DataLancamento { get; set; }

        [Display(Name = "Gênero")]
        [Required(ErrorMessage = "Este campo é obrigatório."),
            StringLength(20),
            RegularExpression(@"^[A-ZÀ-Ý]+[a-zA-ZÀ-ÿ\s]*$", ErrorMessage ="Dados inválidos.")]
        
        public string Genero { get; set; } = string.Empty;

        [Display(Name = "Avaliação")]
        [Range(1,10, ErrorMessage ="Somente valores de 1 a 10.")]
        //[Required(ErrorMessage = "Este campo é obrigatório.")]
        public int Avaliacao { get; set; } = 0;
    }
}

MVCFilmes2025/Models/FilmesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVCFilmes2025.Models
{
    public class FilmesViewModel
    {
        public List<Filme> ? Filmes { get; set; }
        public SelectList ? Generos { get; set; }
        public string? Genero { get; set; }
        public string ? Texto { get; set; }
    }
}

MVCFilmes2025/Controllers/FilmesCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCFilmes2025.Data;
using MVCFilmes2025.Models;

namespace MVCFilmes2025.Controllers
{
    public class FilmesCController : Controller
    {
        private readonly MVCFilmes2025Context _context;

        public FilmesCController(MVCFilmes2025Context context)
        {
            _context = context;
        }

        // GET: FilmesC
        public async Task<IActionResult> Index(string texto, string genero)
        { 
            //query genero
            IQueryable<string> generos = from g in _context.Filme
                                         orderby g.Genero
                                         select g.Genero;
            
            //query para filmes
            var filmes = from f in _context.Filme
                         select f;

            //filtro de filme
            if (!string.IsNullOrWhiteSpace(texto))
            {
                filmes = filmes.Where(s => s.Titulo!.Contains(texto));
            }

            //filtro de genero
            if (!string.IsNullOrWhiteSpace(genero))
            {
                filmes = filmes.Where(s => s.Genero == genero);
            }

            var filmeViewModel = new FilmesViewModel()
            {
                Filmes = await filmes.ToListAsync(),
                Generos = new SelectList(await generos.Distinct().ToListAsync())
            };


            return View(filmeViewModel);
        }

        // GET: FilmesC/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: FilmesC/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FilmesC/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Titulo,DataLancamento,Genero,Avaliacao")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: FilmesC/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            return View(filme);
        }

        // POST: FilmesC/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titulo,DataLancamento,Genero,Avaliacao")] Filme filme)
        {
            if (id != filme.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: FilmesC/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // POST: FilmesC/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filme.FindAsync(id);
            if (filme != null)
            {
                _context.Filme.Remove(filme);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filme.Any(e => e.ID == id);
        }
    }
}

MVCFilmes2025/Controllers/FilmesController.cs
using System.Reflection.Metadata.Ecma335;
using Microsoft.AspNetCore.Mvc;

namespace MVCFilmes2025.Controllers
{
    public class FilmesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BemVindo(string nome, int id)
        {
            ViewData["Title"] = "Boas vindas!";
            ViewData["Nome"] = nome;
            ViewData["id"] = id;
            //string bemvindo = $"Olá! Seja bem-vindo {nome} - {id}!";
            return View();
        }
    }
}

MVCFilmes2025/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCFilmes2025.Models;

namespace MVCFilmes2025.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCFilmes2025/Views/Filmes/BemVindo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Bem-vindo gatinho!</h1>

Olá: @ViewData["Nome"]

@if(ViewData["id"] != null){
    for(int i = 0; i<= Convert.ToInt32(ViewData["id"]); i++)
    {
        
        <span>@i</span>
    }
}

MVCFilmes2025/Views/Filmes/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Lista de filmes";
}

<h1>Filmes index!</h1>

MVCFilmes2025/Views/FilmesC/Create.cshtml
@model MVCFilmes2025.Models.Filme

@{
    ViewData["Title"] = "Create";
}

<h1>Adicionar filme</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para Meus Filmes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCFilmes2025/Views/FilmesC/Delete.cshtml
@model MVCFilmes2025.Models.Filme

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<h3>Tem certeza que deseja excluir este filme? Esta ação é irreversível.</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Sim, desejo excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para Meus Filmes</a>
    </form>
</div>

MVCFilmes2025/Views/FilmesC/Details.cshtml
@model MVCFilmes2025.Models.Filme

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
 
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Editar</a> |
    <a asp-action="Index">Voltar para Meus Filmes</a>
</div>

MVCFilmes2025/Views/FilmesC/Edit.cshtml
@model MVCFilmes2025.Models.Filme

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para Meus Filmes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCFilmes2025/Views/FilmesC/Index.cshtml
@model MVCFilmes2025.Models.FilmesViewModel
@{
    ViewData["Title"] = "Filmes";
}

<h1>Filmes</h1>

<p>
    <a asp-action="Create">Adicionar um filme</a>
</p>

<form asp-controller="FilmesC" asp-action="Index">
    <p>
        Titulo: <input type="text" name="texto"/>
        
        Genero: <select asp-for="Genero" asp-items="Model.Generos">
            <option value="">Todos</option>

        <input type="submit" value="Buscar" />

        
        </select>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].DataLancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Avaliacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Filmes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataLancamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Avaliacao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCFilmes2025/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCFilmes2025/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCFilmes2025</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCFilmes2025.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCFilmes2025</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FilmesC" asp-action="Index">Filmes</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVCFilmes2025 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>